### ISSUE TITLE
Suggestion of more resources

### ISSUE THREAD

**Issue by emdelponte** [research-compendium/research-compendium.github.io#6]
Hi @nuest. I gave a talk at Re:produce workshop in Australia last year. Here are links you may find useful to share here as well

Slides on SpeakerDeck
https://speakerdeck.com/emdelponte/organize-document-and-share-research-data-and-codes-using-r

Webinar
https://www.youtube.com/watch?v=5eW25K_uMbE

**Comment by nuest** [comment]
Thanks you for spreading the word about the website! Apologies for the delay - feel free to ping me any other way next time if I don't react in a few weeks.
